version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite+aiosqlite:///./fraud_shield.db
      - SECRET_KEY=fraud_shield_super_secure_jwt_secret_key_2026
    volumes:
      - ./backend/data:/app/data
      - ./backend/app/ml:/app/app/ml

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - backend
